package Pojos;
// Generated Apr 24, 2020 1:59:53 PM by Hibernate Tools 4.3.1



/**
 * AssignmentSubmission generated by hbm2java
 */
public class AssignmentSubmission  implements java.io.Serializable {


     private Integer assignmentSubmissionId;
     private String subject;
     private String topic;
     private String no;
     private byte[] file;
     private String note;
     private Integer status;
     private String dateTime;
     private Integer userId;

    public AssignmentSubmission() {
    }

    public AssignmentSubmission(String subject, String topic, String no, byte[] file, String note, Integer status, String dateTime, Integer userId) {
       this.subject = subject;
       this.topic = topic;
       this.no = no;
       this.file = file;
       this.note = note;
       this.status = status;
       this.dateTime = dateTime;
       this.userId = userId;
    }
   
    public Integer getAssignmentSubmissionId() {
        return this.assignmentSubmissionId;
    }
    
    public void setAssignmentSubmissionId(Integer assignmentSubmissionId) {
        this.assignmentSubmissionId = assignmentSubmissionId;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


