package Pojos;
// Generated Apr 24, 2020 1:59:53 PM by Hibernate Tools 4.3.1



/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private Integer gradeId;
     private Integer assignmentId;
     private Integer studentId;
     private String grade;
     private String remark;
     private Integer status;
     private String dateTime;
     private String studentFeedback;
     private Integer userId;

    public Grade() {
    }

    public Grade(Integer assignmentId, Integer studentId, String grade, String remark, Integer status, String dateTime, String studentFeedback, Integer userId) {
       this.assignmentId = assignmentId;
       this.studentId = studentId;
       this.grade = grade;
       this.remark = remark;
       this.status = status;
       this.dateTime = dateTime;
       this.studentFeedback = studentFeedback;
       this.userId = userId;
    }

    public Grade(Integer gradeId) {
        this.gradeId = gradeId;
    }
    
   
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
    public Integer getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(Integer assignmentId) {
        this.assignmentId = assignmentId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public String getStudentFeedback() {
        return this.studentFeedback;
    }
    
    public void setStudentFeedback(String studentFeedback) {
        this.studentFeedback = studentFeedback;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


