package Pojos;
// Generated Apr 24, 2020 1:59:53 PM by Hibernate Tools 4.3.1

/**
 * UserRegistration generated by hbm2java
 */
public class UserRegistration implements java.io.Serializable {

    private Integer systemUserId;
    private Integer studentId;
    private String username;
    private String password;
    private String userType;
    private Integer status;
    private String dateTime;
    private Integer userId;

    public UserRegistration() {
    }

    public UserRegistration(Integer studentId, String username, String password, String userType, Integer status, String dateTime, Integer userId) {
        this.studentId = studentId;
        this.username = username;
        this.password = password;
        this.userType = userType;
        this.status = status;
        this.dateTime = dateTime;
        this.userId = userId;
    }

    public UserRegistration(Integer systemUserId) {
        this.systemUserId = systemUserId;
    }

    public Integer getSystemUserId() {
        return this.systemUserId;
    }

    public void setSystemUserId(Integer systemUserId) {
        this.systemUserId = systemUserId;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

}
